### ISSUE TITLE
Cannot see website

### ISSUE THREAD

**Issue by lani0016** [lani0016/ecommerce-pattern-library#3]
Hi Thomas! i am currently having a hard time seeing my website despite following the exercises. And was wondering if it was something with jekyll or my code in general. Please let me know if there is any way to fix this before class on Monday. @thomasjbradley
<img width="567" alt="screen shot 2019-02-02 at 4 42 52 pm" src="https://user-images.githubusercontent.com/31852925/52169634-df890a80-2709-11e9-9ee3-e9892a8b81d1.png">

**Comment by thomasjbradley** [comment]
The error message says that there is a colon missing on line 21. Did you fix the problem?
