### ISSUE TITLE
Request for grade >eCommerce website

### ISSUE THREAD

**Issue by lani0016** [lani0016/ecommerce-pattern-library#6]
Hi @thomasjbradley I would like to input my request for grade.(Even if i'm a little early)

I view my website and the work put in as a "high B" to "low A" range grades wise. The reason behind my self assessed grade is that this website, though completed to the best of my abilities, was a great challenge to my coding experience. I  had multiple outside factors far beyond my control, but I was able to experience each stage of the website almost exactly as if I weren't going through what I did this semester. Though this webpage is far from profesional, I am quite pleased with how much i got to lean buy building my very first ecommerce website that I am proud to say I worked on.

**Comment by thomasjbradley** [comment]
👍

**Comment by thomasjbradley** [comment]
I’m submitting your final grade into ACSIS now.
